### PR TITLE
Add fakehttp

### PR DESCRIPTION
**Pull request by arp242**
Simple library for testing HTTP requests.

There are a bunch of "mock http" libraries, but all are pretty
complicated. I like my testing code simple, and this will cover >90% of
use cases.

### CODE REVIEW

**Comment by cesartw** [comment]
There's already build-in way to test HTTP requests using httptest package https://github.com/Teamwork/deskwebhooks/blob/bc9beba8139201676ea34a3bb1183457ece944d7/app/notifier/webhook_test.go#L12

Also, you could replace the RoundTripper https://golang.org/pkg/net/http/#RoundTripper It has a simpler interface

**Comment by arp242** [comment]
How do you test `http.Client` with `httptest`? AFAIK it's intended for testing handlers.

**Comment by cesartw** [comment]
http.Client needs to make request to httptest.NewServer().URL. That's going to execute your testing handler.

https://play.golang.org/p/2ybD6eQIy-

**Comment by abiosoft** [comment]
You can use `httptest` to create a fake server with expected response. Then use the client to connect to the server url.

**Comment by arp242** [comment]
Ah, right, thanks. Conceptually it seems a bit of a "reverse" way of doing it to me, but it seems to work well :+1:

**Comment by flimzy** [comment]
You can also just use a custom `http.RoundTripper` in the `http.Client` instance to "respond" however you want, without making an actual HTTP connection.

**Comment by arp242** [comment]
Thanks; I'll remember that for next time. I rewrote my tests to `httptest` and that works well :+1:

**Pull request closed without merging**
